### ISSUE TITLE
Unnecessary Sunder Errors

### ISSUE THREAD

**Issue by rprescottjr** [rprescottjr/wow-combatlog-analyzer#8]
When a player does not have **any** unnecessary sunders, a StringIndexOutOfBoundsException is thrown because there is an attempt to access the last index of a comma, but it does not exist.

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.rprescott.combatloganalyzer.CombatLogAnalyzer.getTopUnnecessarySunderMobs(CombatLogAnalyzer.java:245)
	at com.rprescott.combatloganalyzer.CombatLogAnalyzer.analyze(CombatLogAnalyzer.java:125)
	at com.rprescott.combatloganalyzer.CombatLogAnalyzer.main(CombatLogAnalyzer.java:57)
```

**Comment by rprescottjr** [comment]
Issue has been resolved.
